version: "3"
services:
  backend: 
    image: sh80165/product-free-springboot
    container_name: product-be
    restart: always
    ports: 
     - 8080:8080
    networks:
      - app-network
  frontend: 
    image: sh80165/product-free-react
    container_name: product-fe
    restart: always
    ports: 
     - 3000:3000
    networks:
      - app-network
  data: 
    image: sh80165/product-free-data
    container_name: product-data
    restart: always
    ports: 
     - 8000:8000
    networks:
      - app-network
networks:
  app-network: 
    external: true

