api:
  github:
    auth-token: ${GIT_AUTH_TOKEN}
    host: 'https://api.github.com'
  claude:
    api-key: ${CLAUDE_API_KEY}
    host: 'https://api.anthropic.com/v1/messages'
    model: ${CLAUDE_MODEL:claude-sonnet-4-20250514}
logging:
  level:
    com.crm.docs.common.config.websocket: DEBUG
    org:
      springframework:
        web:
          reactive:
            function:
              client: ERROR
        ai:
          mcp:
            SyncMcpToolCallback: DEBUG
          anthropic:
            AnthropicChatModel: DEBUG
          chat:
            client: DEBUG
          tool:
              ToolCallback: DEBUG
              DefaultToolCallingManger: DEBUG
      io:
        modelcontextprotocol: DEBUG
        micrometerL: DEBUG
    reactor:
      netty:
        http:
          client: ERROR
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
spring:
  main:
    allow-bean-definition-overriding: true
  ai:
    anthropic:
      api-key: ${CLAUDE_API_KEY}
      chat:
        options:
          model: ${CLAUDE_MODEL:claude-sonnet-4-20250514}
          temperature: 0.2 #같은 내용이라면 매번 같은 응답을 반환하도록 낮게 설정.
          max-tokens: 10000 #토큰 사용량 줄이기
#    mcp:
#      client:
#        sse:
#          connections:
#            mobile-mcp:
#              url: http://localhost:10000/mcp
    mcp:
      client:
        enabled: true
        type: SYNC
        stdio:
          servers-configuration: classpath:mobile-mcp.json
#      server:
#        transport: SSE
#        sse:
#          enabled: true
    openai: # Embedding 모델
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: ${OPENAI_EMBEDDING_MODEL:text-embedding-3-small}
          dimensions: 1536
    vectorstore:
      pgvector:
        table-name:
        initialize-schema: false
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536 #vector디비와 값을 맞춰야 함.
  datasource:
    url: jdbc:postgresql://localhost:54310/application_analysis_rag
    username: postgres
    password:
